### ISSUE TITLE
Application : Question

### ISSUE THREAD

**Issue by ghost** [Dewep/RouterStats-TP-Link#1]
Hi @Dewep,

Does this application still work or has a lot changed since 3 years?

**Comment by Dewep** [comment]
Hello,

I honestly have no idea, I no longer have this router for over one year now.

I advise you to take a look at this other project that I realized more recently (well, more than 2 years ago), which was also for a TP Link (tested on the firmware 3.13.15): [github.com/Dewep/Network-Chart](https://github.com/Dewep/Network-Chart).
This last one is configurable ([src/interface.html#L135](https://github.com/Dewep/Network-Chart/blob/master/src/interface.html#L135)), and if the firmware is different, you can maybe try to edit this file: [src/js/components/router/tplink.js](https://github.com/Dewep/Network-Chart/blob/master/src/js/components/router/tplink.js).

Have a nice day!

**Comment by ghost** [comment]
@Dewep Thanks
